version: "3"

services:

  back:
    build:
        context: "backend/src/"
        dockerfile: "Dockerfile_backend"
    ports:
      - "7249:7249"
    depends_on: 
      - "db"

  db:
    image: "mysql:latest"
    container_name: "db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "qweasdzxc"
      MYSQL_USER: "mysqluser"
      MYSQL_PASSWORD: "mysqlpassword"
    volumes:
      - "./data:/var/lib/mysql"