FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build

WORKDIR /app

COPY . .

ENV ASPNETCORE_ENVIRONMENT Development
ENV ASPNETCORE_URLS="http://0.0.0.0:5066;https://0.0.0.0:7249"

RUN apk update && apk add --no-cache mysql-client dos2unix mariadb-connector-c

RUN dotnet dev-certs https
RUN dotnet dev-certs https -ep /usr/local/share/ca-certificates/aspnet/https.crt --format PEM
RUN update-ca-certificates

RUN dotnet publish API/AutoHubAPI/AutoHub.API.csproj -c Debug -o /app/publish

RUN dos2unix ./applymigrations.sh
RUN dos2unix ./waitforit.sh
RUN dos2unix ./backend_entrypoint.sh
RUN chmod +x ./applymigrations.sh
RUN chmod +x ./waitforit.sh
RUN chmod +x ./backend_entrypoint.sh

RUN dotnet tool install --global dotnet-ef

ENTRYPOINT ["/bin/sh", "/app/backend_entrypoint.sh"]